# Generated by Django 4.1.6 on 2023-02-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('CARD_ID', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PLATE', models.CharField(default=None, max_length=10)),
                ('MODEL', models.CharField(blank=True, max_length=30)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=50)),
                ('CUSTOMER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
